name = "Death Match";
picture = "DeathMatch/Textures/mod_icon.edds";
logo = "DeathMatch/Textures/mod_icon.edds";
logoSmall = "DeathMatch/Textures/mod_icon.edds";
logoOver = "DeathMatch/Textures/mod_icon.edds";
tooltip = "Death Match";
overview = "This is dealth match mod by Terje Bruoygard.";
author = "Terje Bruoygard";
version = "1.0.0";